# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - "*-hotfix"
    paths:
      # TODO: restore this with AA-1601, except run in a PS-specific
      # workflow, so that the C# build and CodeQL do not run
      # unnecessarily.
      # - "**/*.ps1"
      # - "**/*.psm1"
      - "**/*.cs"
      - "**/*.csproj"
      - "**/packages.lock.json"
      - ".github/**/*.yml"
  workflow_dispatch:

permissions: read-all

jobs:
  # TODO: restore this with AA-1601
  # run-ps-lint:
  #   name: PowerShell Linter
  #   uses: Ed-Fi-Alliance-OSS/Ed-Fi-Actions/.github/workflows/powershell-analyzer.yml@main
  scan-actions-bidi:
    name: Scan Actions, scan all files for BIDI Trojan Attacks
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@8fc2302d7369828b2f0784f8ca219c7da228b583
    with:
      config-file-path: ./.github/workflows/bidi-config.json

  run-linting:
    name: Lint Workflows and YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run actionlint
        uses: rhysd/actionlint@03d0035246f3e81f36aed592ffb4bebf33a03106 # v1.7.7

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: .github/workflows/

  run-cs-tests:
    name: Run C# Tests
    needs: run-linting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Verify NuGet lock files are up to date
        run: dotnet restore Application/Ed-Fi-ODS-AdminApi.sln --locked-mode

      - name: Build
        run: ./build.ps1 -Command Build -Configuration Debug

      - name: Install Coverlet Tools
        if: success()
        run: |
          dotnet tool install --global coverlet.console --version 10.0.1
          dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.5.10

      - name: Run Unit Tests
        if: success()
        run: ./build.ps1 -Command UnitTest -Configuration Debug -RunCoverageAnalysis

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Coverage Report
          path: coveragereport

      - name: Upload Test Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: csharp-tests
          path: "**/*.trx"
          retention-days: 5

      - name: Dependency Review ("Dependabot on PR")
        if: ${{ !github.event.repository.fork }}
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0

      - name: Initialize CodeQL
        if: success()
        uses: github/codeql-action/init@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          languages: csharp, actions

      # Must build the software after initialization of CodeQL; something about
      # CodeQL initialization causes the resulting build to fail unit tests.
      # Therefore rebuilding here, even though also built above.
      - name: Build
        run: ./build.ps1 -Command Build -Configuration Debug

      - name: Perform CodeQL Analysis
        if: success()
        uses: github/codeql-action/analyze@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2

      - name: Upload built application
        if: success()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: built-application
          path: Application
          retention-days: 1

  run-integration-tests:
    name: Run integration tests
    needs: run-cs-tests
    env:
      DB_Password: P@55w0rd
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: pwsh
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server@sha256:d7f2c670f0cd807b4dc466b8887bd2b39a4561f624c154896f5564ea38efd13a
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: ${{ env.DB_Password }}
          MSSQL_ENABLE_HADR: "1"
        ports:
          - 1433:1433
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Download built application
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: built-application
          path: Application

      - name: Run Integration Tests
        if: success()
        run: ./build.ps1 -Command IntegrationTest -Configuration Debug -UseIntegratedSecurity:$false -DbUsername "sa" -DbPassword ${{ env.DB_Password }}

      - name: Upload Test Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: csharp-integration-tests
          path: "**/*.trx"
          retention-days: 5

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Event File
        path: ${{ github.event_path }}
